server:
  address: localhost
  port: 5478
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://127.0.0.1:3306/online_food_order_schema?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #  redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8